baseurl = "https://mrodobbe.github.io/"
title = "Maarten Dobbelaere"
theme = "pulp"
GoogleAnalyticsID = "G-9YTXZQFXW7"
canonifyurls = true
hasCJKLanguage = true
publishDir = "docs"
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "G-9YTXZQFXW7"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Maarten Dobbelaere"
    avatar = "pic.jpg"
    # avatarDescription = "My avatar description"
    favicon = "atom.ico"
    description = """
        I am a postdoctoral researcher at Ghent University's Laboratory for Chemical Technology, working on AI for chemistry. 
        In May 2025, I obtained my Ph.D. thesis titled "Molecular Machine Learning for Chemical Reaction Engineering", 
        supervised by Kevin Van Geem and Christian Stevens. 
    """
    publicationYear = "2022"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    name = "Scholar" #If display text link, cancel comment out
    pre = "<i class='fas fa-graduation-cap'></i>" 
    url = "https://scholar.google.com/citations?user=cw3DUf0AAAAJ"
    weight = 20

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/M_Dobbelaere"
    weight = 20

[[menu.main]]
    identifier = "bluesky"
    name = "BlueSky"
    pre = "<i class='fa-brands fa-bluesky'></i>"  
    url = "https://bsky.app/profile/maartendobbelaere.bsky.social"
    weight = 25

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/mrodobbe"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:mrodobbe.Dobbelaere@UGent.be"
    weight = 40

[[menu.main]]
    identifier = "thesis"
    name = "Thesis Topics"
    pre = "<i class='fas fa-book'></i>"
    url = "/posts/thesis/"
    weight = 40

[[menu.main]]
    identifier = "cv"
    name = "CV"
    pre = "<i class='fas fa-file-pdf'></i>"
    url = "/cv.pdf" 
    weight = 50
